<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title><?php echo $mp_title; ?></title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta charset="UTF-8" />

		<style type="text/css">
			/* Reset */
			html, body, div, span, iframe, applet, object, h1, h2, h3, h4, h5, h6, p, blockquote, small, strike, strong, sub, sup, tt, var, dl, dt, dd, ul, li, fieldset, form, label, legend, table, caption, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, font, ins, kbd, q, s, samp, tbody, tfoot, thead, tr, th, td {
				margin: 0;
				padding: 0;
				border: 0;
				outline: 0;
				vertical-align: baseline;
				background: transparent;
				font-family: DejaVu Sans, sans-serif;
				font-size: 12px;
			}
			
			html, body {
				background-color: #FFF;
			}
			
			img {
				margin: 0;
				padding: 0;
				border: 0;
				outline: 0;
				text-decoration: none;
				background: transparent;
			}

			ul {
				list-style: none;
			}

			strong {
				font-weight: bold;
			}

			:focus {
				outline: 0;
			}

			table, tr, td {
				margin: 0;
				padding: 0;
				border-spacing: 0;
				border-collapse: collapse;
			}

			body { 
				font-family: DejaVu Sans; 
			}
		</style>
    </head>
    <body>
        <div class="mp-help-document-contents"><?php echo $mp_contents; ?></div>
    </body>
</html>