<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title><?php echo $mp_title; ?></title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta charset="UTF-8" />

		<style type="text/css">
			/* Reset */
			html, body, div, span, iframe, applet, object, h1, h2, h3, h4, h5, h6, p, blockquote, small, strike, strong, sub, sup, tt, var, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, font, ins, kbd, q, s, samp, tbody, tfoot, thead, tr, th, td {
				margin: 0;
				padding: 0;
				border: 0;
				outline: 0;
				vertical-align: baseline;
				background: transparent;
				font-family: DejaVu Sans, sans-serif;
				font-size: 12px;
			}
			
			html, body {
				background-color: #FFF;
			}
			
			img {
				margin: 0;
				padding: 0;
				border: 0;
				outline: 0;
				text-decoration: none;
				background: transparent;
			}

			ul {
				list-style: none;
			}

			strong {
				font-weight: bold;
			}

			:focus {
				outline: 0;
			}

			table, tr, td {
				margin: 0;
				padding: 0;
				border-spacing: 0;
				border-collapse: collapse;
			}

			/* Header */
			header {
				position: fixed;
                top: 0px;
                left: 0px;
                right: 0px;

                height: 45px;
				line-height: 45px;
				
				margin-top: 40px;
				padding-right: 55px;
				padding-left: 55px;
				
				display: block;
				text-align: left;
			}

			header table {
				width: 100%;
				height: 45px;
				margin: 0;
				padding: 0;
			}

			header table td { 
				height: 45px;
				margin: 0;
				padding: 0;
			}

			header table td:first-of-type { 
				width: 55px;
			}

			header img.mp-manual-logo {
				text-align: left;
				width: 45px;
				height: 45px;
				border-radius: 9px;
			}

			header div.mp-manual-title {
				color: gray;
				font-size: 11px;
				height: 45px;
				line-height: 12px;
				vertical-align: middle;
				margin: 0;
				margin-top: 5px;
				padding: 0;
			}

			/* Generic document setup */
			@page { 
				margin: 55px; 
				font-family: DejaVu Sans; 
			}
			body {
				font-family: DejaVu Sans; 
				margin: 55px; 
				margin-top: 95px;
			}

			/* Cover page setup */
			h1.mp-manual-cover-title {
				margin-top: 350px;
				text-align: center;
				font-size: 45px;
			}

			h2.mp-manual-cover-subtitle {
				text-align: center;
				color: gray;
				font-size: 25px;
			}

			h3.mp-manual-cover-subtitle {
				text-align: center;
				color: gray;
				font-size: 15px;
				font-weight: normal;
			}

			/* Generic page block setup */
			.mp-page-break  {
				page-break-after: always;
			}

			.mp-help-document-cover {
				page-break-after: always;
			}

			.mp-page-contents-block {
				page-break-after: always;
			}

			.mp-page-contents-block:last-of-type {
				page-break-after: auto;
			}

			.mp-page-contents-block h1 { 
				font-size: 20px;
				color: darkcyan;
				margin-bottom: 15px;
			}

			.mp-page-contents-block h2 {
				font-size: 15px;
				margin-bottom: 10px;
			}

			.mp-page-contents-block p,
			.mp-page-contents-block ul {
				margin-bottom: 10px;
				font-size: 13px;
			}

			.mp-page-contents-block ul,
			.mp-page-contents-block ul li { 
				list-style-type: circle;
			}

			.mp-page-contents-block ul { 
				list-style-type: circle;
				margin-left: 25px;
			}

			.mp-page-contents-block ol { 
				margin-left: 25px;
			}

			.mp-page-contents-block code {
				font-family: 'Courier New', Courier, monospace;
				font-weight: bold;
			}

			.mp-page-contents-block img {
				width: 90%;
				padding-top: 25px;
				box-shadow: 0 0 5px 2px rgba(0, 0, 0, 0.3);
				border-radius: 5px;
				margin-bottom: 10px;
				text-align: center;
			}

			.mp-page-contents-block li img {
				width: 85%;
				margin-left: -10px;
			}
		</style>
    </head>
    <body>
		<div class="mp-help-document-cover"><?php echo $mp_cover; ?></div>
		<header class="mp-help-document-header">
			<?php echo $mp_page_header; ?>
		</header>
		<div class="mp-help-document-contents"><?php echo $mp_contents; ?></div>
    </body>
</html>